## PQR rotation example

Rotation test with a rotation for 180 deg of zika virus with respect to z-axis. We can check that x_rotated = -x and y_rotated = -y

In [8]:
import MDAnalysis as mda
from MDAnalysis import transformations
import numpy as np

zika_origin = mda.Universe('pqr/ZIKV_6CO8_aa_charge_vdw_addspace.pqr')
zika = mda.Universe('pqr/ZIKV_6CO8_aa_charge_vdw_addspace.pqr')

In [3]:
zika_origin.atoms.positions, zika_origin.atoms.positions.shape # File atoms positions

(array([[-158.378,  -64.7  , -129.804],
        [-159.515,  -65.576, -129.445],
        [-159.178,  -66.976, -129.96 ],
        ...,
        [ -91.22 ,  146.41 ,   73.082],
        [ -91.007,  149.585,   75.407],
        [ -90.401,  146.744,   72.613]], dtype=float32),
 (1576628, 3))

In [4]:
# Rotation using MDAnalysis example
ts = zika.trajectory.ts
angle = 180 # Angle in degrees
ag = zika.atoms
d = [0,0,1] # direction of a custom axis of rotation from the provided point
rotated = transformations.rotate.rotateby(angle, direction=d, ag=ag)(ts)

In [5]:
rotated.positions, rotated.positions.shape # Rotated atoms positions

(array([[ 158.38007,   64.70003, -129.804  ],
        [ 159.51706,   65.57603, -129.445  ],
        [ 159.18005,   66.97603, -129.96   ],
        ...,
        [  91.22207, -146.40997,   73.082  ],
        [  91.00907, -149.58498,   75.407  ],
        [  90.40307, -146.74397,   72.613  ]], dtype=float32),
 (1576628, 3))

In [6]:
# Safety check
check_x_axis = np.where(abs((zika_origin.atoms.positions[:,0] - -zika.atoms.positions[:,0]))>1e-2)
check_y_axis = np.where(abs((zika_origin.atoms.positions[:,1] - -zika.atoms.positions[:,1]))>1e-2)
check_z_axis = np.where(abs((zika_origin.atoms.positions[:,2] - -zika.atoms.positions[:,2]))>1e-2)
check_x_axis, check_y_axis, check_z_axis

((array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([      0,       1,       2, ..., 1576625, 1576626, 1576627],
        dtype=int64),))

In [11]:
# Saving name file in pqr format
rotation_axis = np.argmax(d)
direction_to_string = lambda x : 'x-axis' if x == 0 else 'y-axis' if x == 1 else 'z-axis'
zika.atoms.write('zika_rotation_angle%2d_%s.pqr'%(angle, direction_to_string(rotation_axis)))

In [48]:
zika.atoms.ids, zika.atoms.names, zika.atoms.resnames, zika.atoms.segids, zika.atoms.resnums, zika.atoms.charges, zika.atoms.radii

(array([    1,     2,     3, ..., 76626, 76627, 76628]),
 array(['N', 'CA', 'C', ..., 'OG', 'OXT', 'HG'], dtype=object),
 array(['ILE', 'ILE', 'ILE', ..., 'SER', 'SER', 'SER'], dtype=object),
 array(['A', 'A', 'A', ..., 'F', 'F', 'F'], dtype=object),
 array([ 1,  1,  1, ..., 75, 75, 75]),
 array([ 0.031     ,  0.026     ,  0.61199999, ..., -0.65100002,
        -0.81300002,  0.447     ]),
 array([1.824     , 1.90799999, 1.90799999, ..., 1.72099996, 1.66100001,
        0.        ]))